// Auth
export const LOGIN = 'LOGIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const AUTH_TOKEN = 'AUTH_TOKEN'

// Projects
export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE'

// Companies
export const LOAD_COMPANIES = 'LOAD_COMPANIES'
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS'
export const LOAD_COMPANIES_FAILURE = 'LOAD_COMPANIES_FAILURE'

export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE'

export const SAVE_COMPANY = 'SAVE_COMPANY'
export const SAVE_COMPANY_SUCCESS = 'SAVE_COMPANY_SUCCESS'
export const SAVE_COMPANY_FAILURE = 'SAVE_COMPANY_FAILURE'
export const EDIT_COMPANY = 'EDIT_COMPANY'

export const TOGGLE_SAVE_COMPANY_SUCCESS = 'TOGGLE_SAVE_COMPANY_SUCCESS'

// Reports
export const LOAD_REPORTS = 'LOAD_REPORTS'
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS'
export const LOAD_REPORTS_FAILURE = 'LOAD_REPORTS_FAILURE'
export const GENERATE_REPORT = 'GENERATE_REPORT'
export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS'
export const GENERATE_REPORT_FAILURE = 'GENERATE_REPORT_FAILURE'

// Report
export const EDIT_REPORT = 'EDIT_REPORT'
export const SAVE_REPORT = 'SAVE_REPORT'
export const SAVE_REPORT_SUCCESS = 'SAVE_REPORT_SUCCESS'
export const SAVE_REPORT_FAILURE = 'SAVE_REPORT_FAILURE'

export const TOGGLE_SAVE_REPORT_SUCCESS = 'TOGGLE_SAVE_REPORT_SUCCESS'


// Phases
export const LOAD_PHASES = 'LOAD_PHASES'
export const LOAD_PHASES_SUCCESS = 'LOAD_PHASES_SUCCESS'
export const LOAD_PHASES_FAILURE = 'LOAD_PHASES_FAILURE'

export const GET_PHASE = 'GET_PHASE'
export const GET_PHASE_SUCCESS = 'GET_PHASE_SUCCESS'
export const GET_PHASE_FAILURE = 'GET_PHASE_FAILURE'

// Findings
export const LOAD_FINDINGS = 'LOAD_FINDINGS'
export const LOAD_FINDINGS_SUCCESS = 'LOAD_FINDINGS_SUCCESS'
export const LOAD_FINDINGS_FAILURE = 'LOAD_FINDINGS_FAILURE'

export const GET_FINDING = 'GET_FINDING'
export const GET_FINDING_SUCCESS = 'GET_FINDING_SUCCESS'
export const GET_FINDING_FAILURE = 'GET_FINDING_FAILURE'

// Finding
export const SAVE_FINDING = 'SAVE_FINDING'
export const SAVE_FINDING_SUCCESS = 'SAVE_FINDING_SUCCESS'
export const SAVE_FINDING_FAILURE = 'SAVE_FINDING_FAILURE'
export const EDIT_FINDING = 'EDIT_FINDING'
export const TOGGLE_SAVE_FINDING_SUCCESS = 'TOGGLE_SAVE_FINDING_SUCCESS'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'

// User
export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE'

export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES'
export const UPDATE_FAVOURITES_SUCCESS = 'UPDATE_FAVOURITES_SUCCESS'
export const UPDATE_FAVOURITES_FAILURE = 'UPDATE_FAVOURITES_FAILURE'