// Auth
export const LOGIN = 'LOGIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const AUTH_TOKEN = 'AUTH_TOKEN'

// Projects
export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE'

// Companies
export const LOAD_COMPANIES = 'LOAD_COMPANIES'
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS'
export const LOAD_COMPANIES_FAILURE = 'LOAD_COMPANIES_FAILURE'

// Reports
export const LOAD_REPORTS = 'LOAD_REPORTS'
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS'
export const LOAD_REPORTS_FAILURE = 'LOAD_REPORTS_FAILURE'
export const GENERATE_REPORT = 'GENERATE_REPORT'
export const GENERATE_REPORT_SUCCESS = 'GENERATE_REPORT_SUCCESS'
export const GENERATE_REPORT_FAILURE = 'GENERATE_REPORT_FAILURE'

// Report
export const EDIT_REPORT = 'EDIT_REPORT'
export const SAVE_REPORT = 'SAVE_REPORT'
export const SAVE_REPORT_SUCCESS = 'SAVE_REPORT_SUCCESS'
export const SAVE_REPORT_FAILURE = 'SAVE_REPORT_FAILURE'

// Phases
export const LOAD_PHASES = 'LOAD_PHASES'
export const LOAD_PHASES_SUCCESS = 'LOAD_PHASES_SUCCESS'
export const LOAD_PHASES_FAILURE = 'LOAD_PHASES_FAILURE'

// Findings
export const LOAD_FINDINGS = 'LOAD_FINDINGS'
export const LOAD_FINDINGS_SUCCESS = 'LOAD_FINDINGS_SUCCESS'
export const LOAD_FINDINGS_FAILURE = 'LOAD_FINDINGS_FAILURE'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'