// Auth
export const LOGIN = 'LOGIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const AUTH_TOKEN = 'AUTH_TOKEN'

// Projects
export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE'

// Companies
export const LOAD_COMPANIES = 'LOAD_COMPANIES'
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS'
export const LOAD_COMPANIES_FAILURE = 'LOAD_COMPANIES_FAILURE'